# code_quality:
#   stage: test
#   image: "cirrusci/flutter:2.2.2"
#   before_script:
#     - pub global activate dart_code_metrics
#     - export PATH="$PATH":"$HOME/.pub-cache/bin"
#   script:
#     - metrics lib -r codeclimate  > gl-code-quality-report.json
#   artifacts:
#     reports:
#       codequality: gl-code-quality-report.json

test:
  stage: test
  image: "cirrusci/flutter:2.2.2"
  before_script:
    # - pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter pub get
  script:
    flutter build linux
    # - flutter test --machine --coverage | tojunit -o report.xml
    # - lcov --summary coverage/lcov.info
    # - genhtml coverage/lcov.info --output=coverage
  # coverage: '/lines\.*: \d+\.\d+\%/'
  # artifacts:
  #   name: coverage
  #   paths:
  #     - $CI_PROJECT_DIR/coverage
  #   reports:
  #     junit: report.xml
