name: uni_party
description: A new Flutter project.

publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.1.5
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.1.0
  convert: ^3.0.1
  crypto: ^3.0.1
  dart_vlc: ^0.1.8
  device_info_plus: ^2.1.0
  device_preview: ^0.7.4
  dio: ^4.0.0
  encrypt: ^5.0.1
  excel: any
  extended_nested_scroll_view: ^5.0.0
  ffi: ^1.1.2
  file_picker: ^4.1.3
  fijkplayer: ^0.10.0
  flutter_local_notifications: ^8.2.0
  flutter_markdown: ^0.6.6
  flutter_net_captcha: ^2.0.3
  flutter_svg: ^0.22.0
  flutter_webrtc: ^0.6.10+hotfix.1
  fk_user_agent: ^2.0.1
  get: ^4.3.8
  images_picker: ^1.2.4
  jpush_flutter: ^2.1.5
  markdown: ^4.0.0
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  photo_view: ^0.12.0
  protobuf: ^2.0.0
  qr_flutter: ^4.0.0
  scan: ^1.4.3
  shared_preferences: ^2.0.8
  share_plus: ^2.1.4
  sqflite: ^2.0.0+4
  suit: 1.0.0
  timeago: ^3.1.0
  url_launcher: ^6.0.12
  video_player: ^2.2.5
  wakelock: ^0.5.6
  web_socket_channel: ^2.1.0
  webview_flutter: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # dia: ^0.1.3
  # dia_body: ^0.1.2
  # dia_cors: ^0.1.1
  # dia_router: ^0.1.6
  # dia_static: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter_icons:
  image_path: assets/icons/logo/logo.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: '#ffffff'
  image: assets/icons/logo/logo.png
  fullscreen: true

flutter:
  uses-material-design: true
  fonts:
    - family: Iconfont
      fonts:
        - asset: assets/fonts/iconfont/iconfont.ttf
    - family: BalooTammudu2
      fonts:
        - asset: assets/fonts/BalooTammudu2/BalooTammudu2-Bold.ttf
          weight: 700
        - asset: assets/fonts/BalooTammudu2/BalooTammudu2-Medium.ttf
          weight: 500
        - asset: assets/fonts/BalooTammudu2/BalooTammudu2-Regular.ttf
          weight: 400
    - family: SourceHanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansCN/SourceHanSansCN-Normal.otf
          weight: 400

  assets:
    - assets/images/
    - assets/icons/common/
    - assets/icons/events/
    - assets/icons/logo/
    - assets/icons/tools/
