name: uni_party
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amap_flutter_location: ^2.0.0
  cached_network_image: ^3.0.0
  crypto: ^3.0.1
  device_info_plus: ^1.0.1
  device_preview: ^0.7.3
  dio: ^4.0.0
  encrypt: ^5.0.0
  event_bus: ^2.0.0
  ffi: ^1.1.2
  file_picker: ^3.0.2+2
  flutter_svg: ^0.22.0
  get: ^4.1.4
  images_picker: ^1.2.4
  path_provider: ^2.0.2
  permission_handler: ^8.0.1
  qr_flutter: ^4.0.0
  scan: ^1.4.3
  shared_preferences: ^2.0.6
  share_plus: ^2.1.2
  suit: 1.0.0
  video_player: ^2.1.5
  web_socket_channel: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
