name: build and release apk

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm64 --split-per-abi -v
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          asset_name: uparty_${{ github.ref }}_arm64-v8a.apk
          tag: ${{ github.ref }}
          overwrite: false
          prerelease: false
